{
 "title": "event_analysis",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "eventname",
    "label": "event name",
    "query": "select  distinct event_name  from problems en "
   }
  ]
 },
 "panels": [
  { "title": "Global information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Duration impact by Event Name",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\", event_name as metric\nFROM daily_problems\nWHERE $__timeFilter(start)\nGROUP BY event_name\nORDER BY value desc limit 10"
    }
   ]
  },
  {
   "title": "Request impacted by Event Name",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(event_total_request) as \"value\", event_name as metric\nFROM daily_problems\nWHERE $__timeFilter(start)\nGROUP BY event_name\nORDER BY value desc limit 10"
    }
   ]
  },
  { "title": "Event detail", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Problems",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct  problem) as problems\nFROM daily_problems\nWHERE $__timeFilter(start) and  event_name=\"$eventname\" \n\n"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\", impact as metric\nFROM daily_problems\nWHERE $__timeFilter(start) and event_name = '$eventname'\nGROUP BY impact\nORDER BY value desc"
    }
   ]
  },
  {
   "title": "Total Impact Duration By Severity",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\", severity as metric\nFROM daily_problems\nWHERE $__timeFilter(start) and event_name = '$eventname'\nGROUP BY severity\nORDER BY value desc"
    }
   ]
  },
  {
   "title": "Total Impact Request By Severity",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(event_total_request) as \"value\", severity as metric\nFROM daily_problems\nWHERE $__timeFilter(start) and event_name = '$eventname'\nGROUP BY severity\nORDER BY value desc"
    }
   ]
  },
  {
   "title": "Total Impact Duration By Type",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\", event_type as metric\nFROM daily_problems\nWHERE $__timeFilter(start) and event_name = '$eventname'\nGROUP BY event_type\nORDER BY value desc limit 5"
    }
   ]
  },
  {
   "title": "Request impacted by day of month",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nsum(event_total_request) as \"value\", \nCAST( DAYOFMONTH(start) as char) as legend\nFROM daily_problems\nWHERE $__timeFilter(start) and event_name = '$eventname'\nGROUP BY CAST( DAYOFMONTH(start) as char)\nORDER BY value desc limit 5"
    }
   ]
  },
  {
   "title": "Total Impact Duration of Problems",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\", DAYNAME(start) as metric\nFROM daily_problems\nWHERE $__timeFilter(start) and event_name = '$eventname'\nGROUP BY DAYNAME(start)\nORDER BY value desc"
    }
   ]
  },
  {
   "title": "Event Methods",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\", event_method \nFROM daily_problems\nWHERE $__timeFilter(start) and event_name = '$eventname'\nGROUP BY event_method\nORDER BY value desc limit 5"
    }
   ]
  },
  {
   "title": "Event Methods Request",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nsum(event_total_request) as \"value\",  event_method\nFROM daily_problems\nWHERE $__timeFilter(start) and event_name = '$eventname'\nGROUP BY event_method\nORDER BY value desc limit 5"
    }
   ]
  },
  {
   "title": "Daily Event Severity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  event_severity,\n  event_total_request \nFROM daily_problems\nWHERE\n  $__timeFilter(start) and event_name = '$eventname'\nORDER BY start"
    }
   ]
  },
  {
   "title": "Related events",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n   sum(event_total_request),\n   event_name\nFROM daily_problems \nWHERE\n  $__timeFilter(start) and problem in (select problem from daily_problems where event_name = '$eventname')\n  and event_name <> '$eventname'\ngroup by event_name \norder by  sum(event_total_request) desc\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Related events",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n   sum(event_total_request),\n   event_method\nFROM daily_problems \nWHERE\n  $__timeFilter(start) and problem in (select problem from daily_problems where event_name = '$eventname')\n  and event_name <> '$eventname'\ngroup by event_method \norder by  sum(event_total_request) desc\nlimit 5\n"
    }
   ]
  },
  {
   "title": "Daily Event Severity",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n  display_name, start, duration, event_total_request\nFROM daily_problems\nWHERE\n  $__timeFilter(start) and event_name = '$eventname'\nORDER BY start desc"
    }
   ]
  }
 ]
}