{
 "title": "problems_overview",
 "time": { "from": "now-1y", "to": "now" },
 "panels": [
  {
   "title": "Problems",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct  problem) as problems\nFROM problems\nWHERE $__timeFilter(start)\n\n"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\", impact as metric\nFROM problems\nWHERE $__timeFilter(start)\nGROUP BY impact\nORDER BY value desc"
    }
   ]
  },
  {
   "title": "Total Impact Duration By Severity",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\", severity as metric\nFROM problems\nWHERE $__timeFilter(start)\nGROUP BY severity\nORDER BY value desc"
    }
   ]
  },
  {
   "title": "Total Impact Request By Severity",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(event_total_request) as \"value\", severity as metric\nFROM problems\nWHERE $__timeFilter(start)\nGROUP BY severity\nORDER BY value desc"
    }
   ]
  },
  {
   "title": "Total Impact Duration By Type",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\", event_type as metric\nFROM problems\nWHERE $__timeFilter(start)\nGROUP BY event_type\nORDER BY value desc limit 5"
    }
   ]
  },
  {
   "title": "Impact Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "rawSql": "SELECT  start as time, DAYNAME(start) , duration as duration\nFROM problems\nWHERE $__timeFilter(start)\norder by start"
    }
   ]
  },
  {
   "title": "Impact request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT  start as time, DAYNAME(start) , event_total_request as requests\nFROM problems\nWHERE $__timeFilter(start)\norder by start"
    }
   ]
  },
  {
   "title": "Event Severity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  event_severity,\n  event_total_request \nFROM problems\nWHERE\n  $__timeFilter(start)\nORDER BY start"
    }
   ]
  },
  {
   "title": "Hourly Severity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "rawSql": "SELECT\n  start AS \"time\",\n  event_severity,\n  HOUR(start) as hour \nFROM problems\nWHERE\n  $__timeFilter(start)\nORDER BY start"
    }
   ]
  },
  {
   "title": "Duration impact by Event Name",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\", event_name as metric\nFROM problems\nWHERE $__timeFilter(start)\nGROUP BY event_name\nORDER BY value desc limit 10"
    }
   ]
  },
  {
   "title": "Request impacted by Event Name",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(event_total_request) as \"value\", event_name as metric\nFROM problems\nWHERE $__timeFilter(start)\nGROUP BY event_name\nORDER BY value desc limit 10"
    }
   ]
  },
  {
   "title": "Duration impact by Root Cause",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\", event_name as metric\nFROM problems\nWHERE $__timeFilter(start) and root = True\nGROUP BY event_name\nORDER BY value desc limit 10"
    }
   ]
  },
  {
   "title": "Duration impact by Service Method",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(duration) as \"value\",   event_service, event_method as metric\nFROM problems\nWHERE $__timeFilter(start) and root = True\nGROUP BY event_service, event_method\nORDER BY value desc limit 10"
    }
   ]
  }
 ]
}