# config file version
apiVersion: 1

datasources:
  # <string, required> name of the datasource. Required
  - name: Prometheus
    # <string, required> datasource type. Required
    type: prometheus        
    # <string> url
    url: http://prometheus:9090
    # <string> Deprecated, use secureJsonData.password    
    version: 1
    # <bool> allow users to edit datasources from the UI.
    editable: true